# The seil-r2 workspace, built with colcon on top of the base image.
#
#   docker build -f docker/Dockerfile.base -t iddmbse-seil-r2-base .
#   docker build -f docker/Dockerfile.ros2 -t iddmbse-seil-r2-ros2 .
#
# The build context is the workspace root (the directory holding src/).

ARG BASE_IMAGE_ARG=iddmbse-seil-r2-base
FROM ${BASE_IMAGE_ARG} AS ros2

SHELL ["/bin/bash", "-c"]
ENV DEBIAN_FRONTEND=noninteractive

COPY src ${WORKSPACE_PATH}/src

RUN source /opt/ros/${ROS2_DISTRO}/setup.bash && \
    cd ${WORKSPACE_PATH} && \
    colcon build --symlink-install --event-handlers console_direct+

RUN echo "source ${WORKSPACE_PATH}/install/local_setup.bash" >> ${DOCKER_USER_HOME}/.bashrc

WORKDIR ${WORKSPACE_PATH}
ENTRYPOINT ["/entrypoint.sh"]
CMD ["bash"]
